
package gr.manousos.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-14T21:57:35.414+02:00
 * Generated source version: 2.7.0
 * 
 */
public final class DocumentSrv_DocumentSrvImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.manousos.gr/", "DocumentSrvImplService");

    private DocumentSrv_DocumentSrvImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DocumentSrvImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DocumentSrvImplService ss = new DocumentSrvImplService(wsdlURL, SERVICE_NAME);
        DocumentSrv port = ss.getDocumentSrvImplPort();  
        
        {
        System.out.println("Invoking getE2DocById...");
        int _getE2DocById_arg0 = -2028093573;
        int _getE2DocById_arg1 = -957963074;
        gr.manousos.service.E2 _getE2DocById__return = port.getE2DocById(_getE2DocById_arg0, _getE2DocById_arg1);
        System.out.println("getE2DocById.result=" + _getE2DocById__return);


        }
        {
        System.out.println("Invoking test...");
        java.lang.String _test_arg0 = "_test_arg01400954640";
        java.lang.String _test__return = port.test(_test_arg0);
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking finalSubmitE2...");
        gr.manousos.service.E2 _finalSubmitE2_arg0 = new gr.manousos.service.E2();
        java.util.List<gr.manousos.service.E2Estate> _finalSubmitE2_arg0E2Estates = new java.util.ArrayList<gr.manousos.service.E2Estate>();
        gr.manousos.service.E2Estate _finalSubmitE2_arg0E2EstatesVal1 = new gr.manousos.service.E2Estate();
        _finalSubmitE2_arg0E2EstatesVal1.setArea(0.70558494f);
        gr.manousos.service.E2 _finalSubmitE2_arg0E2EstatesVal1E2 = new gr.manousos.service.E2();
        java.util.List<gr.manousos.service.E2Estate> _finalSubmitE2_arg0E2EstatesVal1E2E2Estates = new java.util.ArrayList<gr.manousos.service.E2Estate>();
        _finalSubmitE2_arg0E2EstatesVal1E2.getE2Estates().addAll(_finalSubmitE2_arg0E2EstatesVal1E2E2Estates);
        java.util.List<gr.manousos.service.E2OtherEstate> _finalSubmitE2_arg0E2EstatesVal1E2E2OtherEstates = new java.util.ArrayList<gr.manousos.service.E2OtherEstate>();
        _finalSubmitE2_arg0E2EstatesVal1E2.getE2OtherEstates().addAll(_finalSubmitE2_arg0E2EstatesVal1E2E2OtherEstates);
        gr.manousos.service.E2Id _finalSubmitE2_arg0E2EstatesVal1E2Id = new gr.manousos.service.E2Id();
        _finalSubmitE2_arg0E2EstatesVal1E2Id.setTaxierId(445856219);
        _finalSubmitE2_arg0E2EstatesVal1E2Id.setYear(947566506);
        _finalSubmitE2_arg0E2EstatesVal1E2.setId(_finalSubmitE2_arg0E2EstatesVal1E2Id);
        _finalSubmitE2_arg0E2EstatesVal1E2.setIsComplete(Integer.valueOf(-1870235922));
        gr.manousos.service.Taxpayer _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer = new gr.manousos.service.Taxpayer();
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setAfm("Afm-1975840318");
        gr.manousos.service.Contact _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact = new gr.manousos.service.Contact();
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact.setCell("Cell-1516677527");
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact.setContactId(Integer.valueOf(-867292768));
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact.setEmail("Email1937883898");
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact.setFax("Fax1955054189");
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact.setPhone("Phone-40287142");
        java.util.List<gr.manousos.service.Taxpayer> _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact.getTaxpayers().addAll(_finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContactTaxpayers);
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setContact(_finalSubmitE2_arg0E2EstatesVal1E2TaxpayerContact);
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setFatherName("FatherName1894725054");
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setFname("Fname-924017001");
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setId(Integer.valueOf(-660850523));
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setLname("Lname1167675502");
        gr.manousos.service.User _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser = new gr.manousos.service.User();
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser.setActive(604142132);
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser.setOtp("Otp1882297086");
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser.setPassword("Password1930604980");
        java.util.List<gr.manousos.service.Taxpayer> _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser.getTaxpayers().addAll(_finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUserTaxpayers);
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser.setUserId(Integer.valueOf(171542425));
        _finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser.setUserName("UserName-31223785");
        _finalSubmitE2_arg0E2EstatesVal1E2Taxpayer.setUser(_finalSubmitE2_arg0E2EstatesVal1E2TaxpayerUser);
        _finalSubmitE2_arg0E2EstatesVal1E2.setTaxpayer(_finalSubmitE2_arg0E2EstatesVal1E2Taxpayer);
        _finalSubmitE2_arg0E2EstatesVal1.setE2(_finalSubmitE2_arg0E2EstatesVal1E2);
        java.util.List<gr.manousos.service.E2CoOwner> _finalSubmitE2_arg0E2EstatesVal1E2CoOwners = new java.util.ArrayList<gr.manousos.service.E2CoOwner>();
        _finalSubmitE2_arg0E2EstatesVal1.getE2CoOwners().addAll(_finalSubmitE2_arg0E2EstatesVal1E2CoOwners);
        _finalSubmitE2_arg0E2EstatesVal1.setEstateId(Integer.valueOf(35976326));
        _finalSubmitE2_arg0E2EstatesVal1.setFrom(-57194641);
        _finalSubmitE2_arg0E2EstatesVal1.setLocation("Location235233254");
        _finalSubmitE2_arg0E2EstatesVal1.setMonthlyRental(0.9749572f);
        _finalSubmitE2_arg0E2EstatesVal1.setPosition("Position1956384805");
        _finalSubmitE2_arg0E2EstatesVal1.setRersentCoOwner(0.069746554f);
        _finalSubmitE2_arg0E2EstatesVal1.setRevenueFreeHome(0.17084569f);
        _finalSubmitE2_arg0E2EstatesVal1.setRevenueFreeOffice(0.58663166f);
        _finalSubmitE2_arg0E2EstatesVal1.setRevenuePrivateHotel(0.25017053f);
        _finalSubmitE2_arg0E2EstatesVal1.setRevenuePrivateOffice(0.77392894f);
        _finalSubmitE2_arg0E2EstatesVal1.setTenantAfm("TenantAfm1773361810");
        _finalSubmitE2_arg0E2EstatesVal1.setTenantFullName("TenantFullName822034415");
        _finalSubmitE2_arg0E2EstatesVal1.setTo(-346331268);
        _finalSubmitE2_arg0E2EstatesVal1.setUsage("Usage-1025973555");
        _finalSubmitE2_arg0E2Estates.add(_finalSubmitE2_arg0E2EstatesVal1);
        _finalSubmitE2_arg0.getE2Estates().addAll(_finalSubmitE2_arg0E2Estates);
        java.util.List<gr.manousos.service.E2OtherEstate> _finalSubmitE2_arg0E2OtherEstates = new java.util.ArrayList<gr.manousos.service.E2OtherEstate>();
        gr.manousos.service.E2OtherEstate _finalSubmitE2_arg0E2OtherEstatesVal1 = new gr.manousos.service.E2OtherEstate();
        _finalSubmitE2_arg0E2OtherEstatesVal1.setArea(0.25215608f);
        gr.manousos.service.E2 _finalSubmitE2_arg0E2OtherEstatesVal1E2 = new gr.manousos.service.E2();
        java.util.List<gr.manousos.service.E2Estate> _finalSubmitE2_arg0E2OtherEstatesVal1E2E2Estates = new java.util.ArrayList<gr.manousos.service.E2Estate>();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2.getE2Estates().addAll(_finalSubmitE2_arg0E2OtherEstatesVal1E2E2Estates);
        java.util.List<gr.manousos.service.E2OtherEstate> _finalSubmitE2_arg0E2OtherEstatesVal1E2E2OtherEstates = new java.util.ArrayList<gr.manousos.service.E2OtherEstate>();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2.getE2OtherEstates().addAll(_finalSubmitE2_arg0E2OtherEstatesVal1E2E2OtherEstates);
        gr.manousos.service.E2Id _finalSubmitE2_arg0E2OtherEstatesVal1E2Id = new gr.manousos.service.E2Id();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Id.setTaxierId(363866170);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Id.setYear(95790438);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2.setId(_finalSubmitE2_arg0E2OtherEstatesVal1E2Id);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2.setIsComplete(Integer.valueOf(-83773859));
        gr.manousos.service.Taxpayer _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer = new gr.manousos.service.Taxpayer();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setAfm("Afm647676437");
        gr.manousos.service.Contact _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact = new gr.manousos.service.Contact();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact.setCell("Cell1378155588");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact.setContactId(Integer.valueOf(-32493932));
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact.setEmail("Email-514445440");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact.setFax("Fax-1035152770");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact.setPhone("Phone-637294361");
        java.util.List<gr.manousos.service.Taxpayer> _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact.getTaxpayers().addAll(_finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContactTaxpayers);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setContact(_finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerContact);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setFatherName("FatherName958441113");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setFname("Fname1280599607");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setId(Integer.valueOf(935386232));
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setLname("Lname-831545429");
        gr.manousos.service.User _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser = new gr.manousos.service.User();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser.setActive(-2010353662);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser.setOtp("Otp94161849");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser.setPassword("Password-107527274");
        java.util.List<gr.manousos.service.Taxpayer> _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser.getTaxpayers().addAll(_finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUserTaxpayers);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser.setUserId(Integer.valueOf(-581506913));
        _finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser.setUserName("UserName1112390551");
        _finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer.setUser(_finalSubmitE2_arg0E2OtherEstatesVal1E2TaxpayerUser);
        _finalSubmitE2_arg0E2OtherEstatesVal1E2.setTaxpayer(_finalSubmitE2_arg0E2OtherEstatesVal1E2Taxpayer);
        _finalSubmitE2_arg0E2OtherEstatesVal1.setE2(_finalSubmitE2_arg0E2OtherEstatesVal1E2);
        _finalSubmitE2_arg0E2OtherEstatesVal1.setId(-1564425629);
        _finalSubmitE2_arg0E2OtherEstatesVal1.setLocation("Location1650416806");
        _finalSubmitE2_arg0E2OtherEstatesVal1.setPosition("Position-878838420");
        _finalSubmitE2_arg0E2OtherEstatesVal1.setTitle("Title-832321568");
        _finalSubmitE2_arg0E2OtherEstatesVal1.setUsage("Usage525222124");
        _finalSubmitE2_arg0E2OtherEstates.add(_finalSubmitE2_arg0E2OtherEstatesVal1);
        _finalSubmitE2_arg0.getE2OtherEstates().addAll(_finalSubmitE2_arg0E2OtherEstates);
        gr.manousos.service.E2Id _finalSubmitE2_arg0Id = new gr.manousos.service.E2Id();
        _finalSubmitE2_arg0Id.setTaxierId(1276945101);
        _finalSubmitE2_arg0Id.setYear(-607796826);
        _finalSubmitE2_arg0.setId(_finalSubmitE2_arg0Id);
        _finalSubmitE2_arg0.setIsComplete(Integer.valueOf(977868010));
        gr.manousos.service.Taxpayer _finalSubmitE2_arg0Taxpayer = new gr.manousos.service.Taxpayer();
        _finalSubmitE2_arg0Taxpayer.setAfm("Afm-1575619364");
        gr.manousos.service.Contact _finalSubmitE2_arg0TaxpayerContact = new gr.manousos.service.Contact();
        _finalSubmitE2_arg0TaxpayerContact.setCell("Cell1829214961");
        _finalSubmitE2_arg0TaxpayerContact.setContactId(Integer.valueOf(-259511195));
        _finalSubmitE2_arg0TaxpayerContact.setEmail("Email1683132491");
        _finalSubmitE2_arg0TaxpayerContact.setFax("Fax1972148286");
        _finalSubmitE2_arg0TaxpayerContact.setPhone("Phone-1511061162");
        java.util.List<gr.manousos.service.Taxpayer> _finalSubmitE2_arg0TaxpayerContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _finalSubmitE2_arg0TaxpayerContact.getTaxpayers().addAll(_finalSubmitE2_arg0TaxpayerContactTaxpayers);
        _finalSubmitE2_arg0Taxpayer.setContact(_finalSubmitE2_arg0TaxpayerContact);
        _finalSubmitE2_arg0Taxpayer.setFatherName("FatherName-308447468");
        _finalSubmitE2_arg0Taxpayer.setFname("Fname1522990434");
        _finalSubmitE2_arg0Taxpayer.setId(Integer.valueOf(201289364));
        _finalSubmitE2_arg0Taxpayer.setLname("Lname-1111204469");
        gr.manousos.service.User _finalSubmitE2_arg0TaxpayerUser = new gr.manousos.service.User();
        _finalSubmitE2_arg0TaxpayerUser.setActive(-375069304);
        _finalSubmitE2_arg0TaxpayerUser.setOtp("Otp-1976689181");
        _finalSubmitE2_arg0TaxpayerUser.setPassword("Password-1486938870");
        java.util.List<gr.manousos.service.Taxpayer> _finalSubmitE2_arg0TaxpayerUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _finalSubmitE2_arg0TaxpayerUser.getTaxpayers().addAll(_finalSubmitE2_arg0TaxpayerUserTaxpayers);
        _finalSubmitE2_arg0TaxpayerUser.setUserId(Integer.valueOf(2032695431));
        _finalSubmitE2_arg0TaxpayerUser.setUserName("UserName-1874232492");
        _finalSubmitE2_arg0Taxpayer.setUser(_finalSubmitE2_arg0TaxpayerUser);
        _finalSubmitE2_arg0.setTaxpayer(_finalSubmitE2_arg0Taxpayer);
        gr.manousos.service.E2 _finalSubmitE2__return = port.finalSubmitE2(_finalSubmitE2_arg0);
        System.out.println("finalSubmitE2.result=" + _finalSubmitE2__return);


        }

        System.exit(0);
    }

}
