package gr.manousos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-14T21:57:35.568+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "DocumentSrvImplService", 
                  wsdlLocation = "http://localhost:8088/TaxisNet/services/DocumentSrvImplPort?wsdl",
                  targetNamespace = "http://service.manousos.gr/") 
public class DocumentSrvImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.manousos.gr/", "DocumentSrvImplService");
    public final static QName DocumentSrvImplPort = new QName("http://service.manousos.gr/", "DocumentSrvImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8088/TaxisNet/services/DocumentSrvImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocumentSrvImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8088/TaxisNet/services/DocumentSrvImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocumentSrvImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentSrvImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentSrvImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentSrvImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentSrvImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentSrvImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DocumentSrv
     */
    @WebEndpoint(name = "DocumentSrvImplPort")
    public DocumentSrv getDocumentSrvImplPort() {
        return super.getPort(DocumentSrvImplPort, DocumentSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentSrv
     */
    @WebEndpoint(name = "DocumentSrvImplPort")
    public DocumentSrv getDocumentSrvImplPort(WebServiceFeature... features) {
        return super.getPort(DocumentSrvImplPort, DocumentSrv.class, features);
    }

}
