package gr.manousos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-23T19:32:25.426+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "UserSrvImpl", 
                  wsdlLocation = "http://localhost:8088/TaxisNetTestUI/services/UserSrvImplPort?wsdl",
                  targetNamespace = "http://service.manousos.gr/") 
public class UserSrvImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.manousos.gr/", "UserSrvImpl");
    public final static QName UserSrvImplPort = new QName("http://service.manousos.gr/", "UserSrvImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8088/TaxisNetTestUI/services/UserSrvImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserSrvImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8088/TaxisNetTestUI/services/UserSrvImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserSrvImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserSrvImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserSrvImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserSrvImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserSrvImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserSrvImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserSrvImplPortType
     */
    @WebEndpoint(name = "UserSrvImplPort")
    public UserSrvImplPortType getUserSrvImplPort() {
        return super.getPort(UserSrvImplPort, UserSrvImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserSrvImplPortType
     */
    @WebEndpoint(name = "UserSrvImplPort")
    public UserSrvImplPortType getUserSrvImplPort(WebServiceFeature... features) {
        return super.getPort(UserSrvImplPort, UserSrvImplPortType.class, features);
    }

}
