
package gr.manousos.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-23T19:32:25.278+02:00
 * Generated source version: 2.7.0
 * 
 */
public final class UserSrvImplPortType_UserSrvImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.manousos.gr/", "UserSrvImpl");

    private UserSrvImplPortType_UserSrvImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserSrvImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserSrvImpl ss = new UserSrvImpl(wsdlURL, SERVICE_NAME);
        UserSrvImplPortType port = ss.getUserSrvImplPort();  
        
        {
        System.out.println("Invoking test...");
        java.lang.String _test_msg = "_test_msg-713012307";
        java.lang.String _test__return = port.test(_test_msg);
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking register...");
        gr.manousos.service.Taxpayer _register_user = new gr.manousos.service.Taxpayer();
        _register_user.setAfm("Afm-60902910");
        gr.manousos.service.Contact _register_userContact = new gr.manousos.service.Contact();
        _register_userContact.setCell("Cell1362344719");
        _register_userContact.setContactId(Integer.valueOf(657612788));
        _register_userContact.setEmail("Email1898004275");
        _register_userContact.setFax("Fax-1809277912");
        _register_userContact.setPhone("Phone-1386390046");
        java.util.List<gr.manousos.service.Taxpayer> _register_userContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _register_userContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _register_userContactTaxpayersVal1.setAfm("Afm317076806");
        gr.manousos.service.Contact _register_userContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _register_userContactTaxpayersVal1Contact.setCell("Cell1328712317");
        _register_userContactTaxpayersVal1Contact.setContactId(Integer.valueOf(-1077776567));
        _register_userContactTaxpayersVal1Contact.setEmail("Email1048649515");
        _register_userContactTaxpayersVal1Contact.setFax("Fax-1978305744");
        _register_userContactTaxpayersVal1Contact.setPhone("Phone203699289");
        java.util.List<gr.manousos.service.Taxpayer> _register_userContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_userContactTaxpayersVal1Contact.getTaxpayers().addAll(_register_userContactTaxpayersVal1ContactTaxpayers);
        _register_userContactTaxpayersVal1.setContact(_register_userContactTaxpayersVal1Contact);
        _register_userContactTaxpayersVal1.setFatherName("FatherName-1189283256");
        _register_userContactTaxpayersVal1.setFname("Fname-85635477");
        _register_userContactTaxpayersVal1.setId(Integer.valueOf(-1473026768));
        _register_userContactTaxpayersVal1.setLname("Lname1464029845");
        gr.manousos.service.User _register_userContactTaxpayersVal1User = new gr.manousos.service.User();
        _register_userContactTaxpayersVal1User.setActive(-2006282478);
        _register_userContactTaxpayersVal1User.setOtp("Otp-1182175451");
        _register_userContactTaxpayersVal1User.setPassword("Password-1597479004");
        java.util.List<gr.manousos.service.Taxpayer> _register_userContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_userContactTaxpayersVal1User.getTaxpayers().addAll(_register_userContactTaxpayersVal1UserTaxpayers);
        _register_userContactTaxpayersVal1User.setUserId(Integer.valueOf(303263956));
        _register_userContactTaxpayersVal1User.setUserName("UserName1392657122");
        _register_userContactTaxpayersVal1.setUser(_register_userContactTaxpayersVal1User);
        _register_userContactTaxpayers.add(_register_userContactTaxpayersVal1);
        _register_userContact.getTaxpayers().addAll(_register_userContactTaxpayers);
        _register_user.setContact(_register_userContact);
        _register_user.setFatherName("FatherName727035346");
        _register_user.setFname("Fname-458626128");
        _register_user.setId(Integer.valueOf(-891875164));
        _register_user.setLname("Lname-1795133760");
        gr.manousos.service.User _register_userUser = new gr.manousos.service.User();
        _register_userUser.setActive(-1986514921);
        _register_userUser.setOtp("Otp190076261");
        _register_userUser.setPassword("Password-694708530");
        java.util.List<gr.manousos.service.Taxpayer> _register_userUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _register_userUserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _register_userUserTaxpayersVal1.setAfm("Afm-145738678");
        gr.manousos.service.Contact _register_userUserTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _register_userUserTaxpayersVal1Contact.setCell("Cell-1576356807");
        _register_userUserTaxpayersVal1Contact.setContactId(Integer.valueOf(-1786636257));
        _register_userUserTaxpayersVal1Contact.setEmail("Email-751945232");
        _register_userUserTaxpayersVal1Contact.setFax("Fax-62780746");
        _register_userUserTaxpayersVal1Contact.setPhone("Phone223228880");
        java.util.List<gr.manousos.service.Taxpayer> _register_userUserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_userUserTaxpayersVal1Contact.getTaxpayers().addAll(_register_userUserTaxpayersVal1ContactTaxpayers);
        _register_userUserTaxpayersVal1.setContact(_register_userUserTaxpayersVal1Contact);
        _register_userUserTaxpayersVal1.setFatherName("FatherName1240315182");
        _register_userUserTaxpayersVal1.setFname("Fname1741997641");
        _register_userUserTaxpayersVal1.setId(Integer.valueOf(1821349910));
        _register_userUserTaxpayersVal1.setLname("Lname1366392250");
        gr.manousos.service.User _register_userUserTaxpayersVal1User = new gr.manousos.service.User();
        _register_userUserTaxpayersVal1User.setActive(1541570743);
        _register_userUserTaxpayersVal1User.setOtp("Otp-69317932");
        _register_userUserTaxpayersVal1User.setPassword("Password-168994082");
        java.util.List<gr.manousos.service.Taxpayer> _register_userUserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_userUserTaxpayersVal1User.getTaxpayers().addAll(_register_userUserTaxpayersVal1UserTaxpayers);
        _register_userUserTaxpayersVal1User.setUserId(Integer.valueOf(32701266));
        _register_userUserTaxpayersVal1User.setUserName("UserName-2028318500");
        _register_userUserTaxpayersVal1.setUser(_register_userUserTaxpayersVal1User);
        _register_userUserTaxpayers.add(_register_userUserTaxpayersVal1);
        _register_userUser.getTaxpayers().addAll(_register_userUserTaxpayers);
        _register_userUser.setUserId(Integer.valueOf(1822753687));
        _register_userUser.setUserName("UserName1062135715");
        _register_user.setUser(_register_userUser);
        gr.manousos.service.Taxpayer _register__return = port.register(_register_user);
        System.out.println("register.result=" + _register__return);


        }
        {
        System.out.println("Invoking registerTaxPayer...");
        gr.manousos.service.Taxpayer _registerTaxPayer_user = new gr.manousos.service.Taxpayer();
        _registerTaxPayer_user.setAfm("Afm-1728244510");
        gr.manousos.service.Contact _registerTaxPayer_userContact = new gr.manousos.service.Contact();
        _registerTaxPayer_userContact.setCell("Cell61111066");
        _registerTaxPayer_userContact.setContactId(Integer.valueOf(-1094970052));
        _registerTaxPayer_userContact.setEmail("Email1309327141");
        _registerTaxPayer_userContact.setFax("Fax2107631957");
        _registerTaxPayer_userContact.setPhone("Phone2037695475");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_userContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _registerTaxPayer_userContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _registerTaxPayer_userContactTaxpayersVal1.setAfm("Afm1615392224");
        gr.manousos.service.Contact _registerTaxPayer_userContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _registerTaxPayer_userContactTaxpayersVal1Contact.setCell("Cell777453711");
        _registerTaxPayer_userContactTaxpayersVal1Contact.setContactId(Integer.valueOf(398609712));
        _registerTaxPayer_userContactTaxpayersVal1Contact.setEmail("Email-1543559988");
        _registerTaxPayer_userContactTaxpayersVal1Contact.setFax("Fax-330211542");
        _registerTaxPayer_userContactTaxpayersVal1Contact.setPhone("Phone-1452770308");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_userContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_userContactTaxpayersVal1Contact.getTaxpayers().addAll(_registerTaxPayer_userContactTaxpayersVal1ContactTaxpayers);
        _registerTaxPayer_userContactTaxpayersVal1.setContact(_registerTaxPayer_userContactTaxpayersVal1Contact);
        _registerTaxPayer_userContactTaxpayersVal1.setFatherName("FatherName-810597181");
        _registerTaxPayer_userContactTaxpayersVal1.setFname("Fname-47215593");
        _registerTaxPayer_userContactTaxpayersVal1.setId(Integer.valueOf(-435632737));
        _registerTaxPayer_userContactTaxpayersVal1.setLname("Lname1880222013");
        gr.manousos.service.User _registerTaxPayer_userContactTaxpayersVal1User = new gr.manousos.service.User();
        _registerTaxPayer_userContactTaxpayersVal1User.setActive(-1278972517);
        _registerTaxPayer_userContactTaxpayersVal1User.setOtp("Otp-900006988");
        _registerTaxPayer_userContactTaxpayersVal1User.setPassword("Password-1728589515");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_userContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_userContactTaxpayersVal1User.getTaxpayers().addAll(_registerTaxPayer_userContactTaxpayersVal1UserTaxpayers);
        _registerTaxPayer_userContactTaxpayersVal1User.setUserId(Integer.valueOf(-1973860647));
        _registerTaxPayer_userContactTaxpayersVal1User.setUserName("UserName1041828666");
        _registerTaxPayer_userContactTaxpayersVal1.setUser(_registerTaxPayer_userContactTaxpayersVal1User);
        _registerTaxPayer_userContactTaxpayers.add(_registerTaxPayer_userContactTaxpayersVal1);
        _registerTaxPayer_userContact.getTaxpayers().addAll(_registerTaxPayer_userContactTaxpayers);
        _registerTaxPayer_user.setContact(_registerTaxPayer_userContact);
        _registerTaxPayer_user.setFatherName("FatherName666478996");
        _registerTaxPayer_user.setFname("Fname75481893");
        _registerTaxPayer_user.setId(Integer.valueOf(1599448404));
        _registerTaxPayer_user.setLname("Lname1295821577");
        gr.manousos.service.User _registerTaxPayer_userUser = new gr.manousos.service.User();
        _registerTaxPayer_userUser.setActive(-170916193);
        _registerTaxPayer_userUser.setOtp("Otp1609774341");
        _registerTaxPayer_userUser.setPassword("Password352838324");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_userUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _registerTaxPayer_userUserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _registerTaxPayer_userUserTaxpayersVal1.setAfm("Afm27759501");
        gr.manousos.service.Contact _registerTaxPayer_userUserTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _registerTaxPayer_userUserTaxpayersVal1Contact.setCell("Cell-1037643816");
        _registerTaxPayer_userUserTaxpayersVal1Contact.setContactId(Integer.valueOf(-1786004203));
        _registerTaxPayer_userUserTaxpayersVal1Contact.setEmail("Email-234546624");
        _registerTaxPayer_userUserTaxpayersVal1Contact.setFax("Fax1952871129");
        _registerTaxPayer_userUserTaxpayersVal1Contact.setPhone("Phone940608957");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_userUserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_userUserTaxpayersVal1Contact.getTaxpayers().addAll(_registerTaxPayer_userUserTaxpayersVal1ContactTaxpayers);
        _registerTaxPayer_userUserTaxpayersVal1.setContact(_registerTaxPayer_userUserTaxpayersVal1Contact);
        _registerTaxPayer_userUserTaxpayersVal1.setFatherName("FatherName-551222312");
        _registerTaxPayer_userUserTaxpayersVal1.setFname("Fname1794231434");
        _registerTaxPayer_userUserTaxpayersVal1.setId(Integer.valueOf(1982726211));
        _registerTaxPayer_userUserTaxpayersVal1.setLname("Lname1228744179");
        gr.manousos.service.User _registerTaxPayer_userUserTaxpayersVal1User = new gr.manousos.service.User();
        _registerTaxPayer_userUserTaxpayersVal1User.setActive(488316646);
        _registerTaxPayer_userUserTaxpayersVal1User.setOtp("Otp2017002416");
        _registerTaxPayer_userUserTaxpayersVal1User.setPassword("Password-6650534");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_userUserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_userUserTaxpayersVal1User.getTaxpayers().addAll(_registerTaxPayer_userUserTaxpayersVal1UserTaxpayers);
        _registerTaxPayer_userUserTaxpayersVal1User.setUserId(Integer.valueOf(-423468254));
        _registerTaxPayer_userUserTaxpayersVal1User.setUserName("UserName1194542336");
        _registerTaxPayer_userUserTaxpayersVal1.setUser(_registerTaxPayer_userUserTaxpayersVal1User);
        _registerTaxPayer_userUserTaxpayers.add(_registerTaxPayer_userUserTaxpayersVal1);
        _registerTaxPayer_userUser.getTaxpayers().addAll(_registerTaxPayer_userUserTaxpayers);
        _registerTaxPayer_userUser.setUserId(Integer.valueOf(358283230));
        _registerTaxPayer_userUser.setUserName("UserName791314967");
        _registerTaxPayer_user.setUser(_registerTaxPayer_userUser);
        port.registerTaxPayer(_registerTaxPayer_user);


        }

        System.exit(0);
    }

}
