package gr.manousos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-13T20:25:36.530+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "UserSrvImplService", 
                  wsdlLocation = "http://localhost:8088/TaxisNet/services/UserSrvImplPort?wsdl",
                  targetNamespace = "http://service.manousos.gr/") 
public class UserSrvImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.manousos.gr/", "UserSrvImplService");
    public final static QName UserSrvImplPort = new QName("http://service.manousos.gr/", "UserSrvImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8088/TaxisNet/services/UserSrvImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserSrvImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8088/TaxisNet/services/UserSrvImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserSrvImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserSrvImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserSrvImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserSrvImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserSrvImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserSrvImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserSrv
     */
    @WebEndpoint(name = "UserSrvImplPort")
    public UserSrv getUserSrvImplPort() {
        return super.getPort(UserSrvImplPort, UserSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserSrv
     */
    @WebEndpoint(name = "UserSrvImplPort")
    public UserSrv getUserSrvImplPort(WebServiceFeature... features) {
        return super.getPort(UserSrvImplPort, UserSrv.class, features);
    }

}
