package gr.manousos.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-23T19:32:25.414+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.manousos.gr/", name = "UserSrvImplPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserSrvImplPortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://service.manousos.gr/", className = "gr.manousos.service.Test")
    @WebMethod
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.manousos.gr/", className = "gr.manousos.service.TestResponse")
    public java.lang.String test(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "Register", targetNamespace = "http://service.manousos.gr/", className = "gr.manousos.service.Register")
    @WebMethod(operationName = "Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://service.manousos.gr/", className = "gr.manousos.service.RegisterResponse")
    public gr.manousos.service.Taxpayer register(
        @WebParam(name = "user", targetNamespace = "")
        gr.manousos.service.Taxpayer user
    );

    @RequestWrapper(localName = "RegisterTaxPayer", targetNamespace = "http://service.manousos.gr/", className = "gr.manousos.service.RegisterTaxPayer")
    @WebMethod(operationName = "RegisterTaxPayer")
    @ResponseWrapper(localName = "RegisterTaxPayerResponse", targetNamespace = "http://service.manousos.gr/", className = "gr.manousos.service.RegisterTaxPayerResponse")
    public void registerTaxPayer(
        @WebParam(name = "user", targetNamespace = "")
        gr.manousos.service.Taxpayer user
    );
}
