
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gr.manousos.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-13T20:25:36.487+02:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserSrvImplService",
                      portName = "UserSrvImplPort",
                      targetNamespace = "http://service.manousos.gr/",
                      wsdlLocation = "http://localhost:8088/TaxisNet/services/UserSrvImplPort?wsdl",
                      endpointInterface = "gr.manousos.service.UserSrv")
                      
public class UserSrvImpl implements UserSrv {

    private static final Logger LOG = Logger.getLogger(UserSrvImpl.class.getName());

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrv#test(java.lang.String  arg0 )*
     */
    public java.lang.String test(java.lang.String arg0) { 
        LOG.info("Executing operation test");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-302434089";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrv#getTaxPayerById(int  arg0 )*
     */
    public gr.manousos.service.Taxpayer getTaxPayerById(int arg0) { 
        LOG.info("Executing operation getTaxPayerById");
        System.out.println(arg0);
        try {
            gr.manousos.service.Taxpayer _return = new gr.manousos.service.Taxpayer();
            _return.setAfm("Afm-957752287");
            gr.manousos.service.Contact _returnContact = new gr.manousos.service.Contact();
            _returnContact.setCell("Cell-886403413");
            _returnContact.setContactId(Integer.valueOf(1212594807));
            _returnContact.setEmail("Email-870520093");
            _returnContact.setFax("Fax1959510115");
            _returnContact.setPhone("Phone-1246440230");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            gr.manousos.service.Taxpayer _returnContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
            _returnContactTaxpayersVal1.setAfm("Afm-865243772");
            gr.manousos.service.Contact _returnContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
            _returnContactTaxpayersVal1Contact.setCell("Cell-221914901");
            _returnContactTaxpayersVal1Contact.setContactId(Integer.valueOf(116785050));
            _returnContactTaxpayersVal1Contact.setEmail("Email-1348734294");
            _returnContactTaxpayersVal1Contact.setFax("Fax-1552452883");
            _returnContactTaxpayersVal1Contact.setPhone("Phone1668977367");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnContactTaxpayersVal1Contact.getTaxpayers().addAll(_returnContactTaxpayersVal1ContactTaxpayers);
            _returnContactTaxpayersVal1.setContact(_returnContactTaxpayersVal1Contact);
            _returnContactTaxpayersVal1.setFatherName("FatherName-128068838");
            _returnContactTaxpayersVal1.setFname("Fname-498242841");
            _returnContactTaxpayersVal1.setId(Integer.valueOf(-817486855));
            _returnContactTaxpayersVal1.setLname("Lname-371507637");
            gr.manousos.service.User _returnContactTaxpayersVal1User = new gr.manousos.service.User();
            _returnContactTaxpayersVal1User.setActive(340337594);
            _returnContactTaxpayersVal1User.setOtp("Otp1206295014");
            _returnContactTaxpayersVal1User.setPassword("Password455467635");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnContactTaxpayersVal1User.getTaxpayers().addAll(_returnContactTaxpayersVal1UserTaxpayers);
            _returnContactTaxpayersVal1User.setUserId(Integer.valueOf(675253326));
            _returnContactTaxpayersVal1User.setUserName("UserName1802598567");
            _returnContactTaxpayersVal1.setUser(_returnContactTaxpayersVal1User);
            _returnContactTaxpayers.add(_returnContactTaxpayersVal1);
            _returnContact.getTaxpayers().addAll(_returnContactTaxpayers);
            _return.setContact(_returnContact);
            _return.setFatherName("FatherName1897323976");
            _return.setFname("Fname-1544137316");
            _return.setId(Integer.valueOf(-2138315477));
            _return.setLname("Lname711360373");
            gr.manousos.service.User _returnUser = new gr.manousos.service.User();
            _returnUser.setActive(499482368);
            _returnUser.setOtp("Otp-1218117021");
            _returnUser.setPassword("Password752021147");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            gr.manousos.service.Taxpayer _returnUserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
            _returnUserTaxpayersVal1.setAfm("Afm369656182");
            gr.manousos.service.Contact _returnUserTaxpayersVal1Contact = new gr.manousos.service.Contact();
            _returnUserTaxpayersVal1Contact.setCell("Cell1141841169");
            _returnUserTaxpayersVal1Contact.setContactId(Integer.valueOf(-1170427181));
            _returnUserTaxpayersVal1Contact.setEmail("Email-1660497885");
            _returnUserTaxpayersVal1Contact.setFax("Fax2007259727");
            _returnUserTaxpayersVal1Contact.setPhone("Phone1613144988");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnUserTaxpayersVal1Contact.getTaxpayers().addAll(_returnUserTaxpayersVal1ContactTaxpayers);
            _returnUserTaxpayersVal1.setContact(_returnUserTaxpayersVal1Contact);
            _returnUserTaxpayersVal1.setFatherName("FatherName-1627430708");
            _returnUserTaxpayersVal1.setFname("Fname-1253058117");
            _returnUserTaxpayersVal1.setId(Integer.valueOf(1488962504));
            _returnUserTaxpayersVal1.setLname("Lname904006553");
            gr.manousos.service.User _returnUserTaxpayersVal1User = new gr.manousos.service.User();
            _returnUserTaxpayersVal1User.setActive(-416835595);
            _returnUserTaxpayersVal1User.setOtp("Otp-103518032");
            _returnUserTaxpayersVal1User.setPassword("Password-532804894");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnUserTaxpayersVal1User.getTaxpayers().addAll(_returnUserTaxpayersVal1UserTaxpayers);
            _returnUserTaxpayersVal1User.setUserId(Integer.valueOf(-1166316316));
            _returnUserTaxpayersVal1User.setUserName("UserName1036616433");
            _returnUserTaxpayersVal1.setUser(_returnUserTaxpayersVal1User);
            _returnUserTaxpayers.add(_returnUserTaxpayersVal1);
            _returnUser.getTaxpayers().addAll(_returnUserTaxpayers);
            _returnUser.setUserId(Integer.valueOf(1528325834));
            _returnUser.setUserName("UserName-1938652626");
            _return.setUser(_returnUser);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrv#register(gr.manousos.service.Taxpayer  arg0 )*
     */
    public gr.manousos.service.Taxpayer register(gr.manousos.service.Taxpayer arg0) { 
        LOG.info("Executing operation register");
        System.out.println(arg0);
        try {
            gr.manousos.service.Taxpayer _return = new gr.manousos.service.Taxpayer();
            _return.setAfm("Afm-1634524165");
            gr.manousos.service.Contact _returnContact = new gr.manousos.service.Contact();
            _returnContact.setCell("Cell-249882672");
            _returnContact.setContactId(Integer.valueOf(-539484239));
            _returnContact.setEmail("Email-1724431012");
            _returnContact.setFax("Fax-569896954");
            _returnContact.setPhone("Phone485365703");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            gr.manousos.service.Taxpayer _returnContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
            _returnContactTaxpayersVal1.setAfm("Afm681977996");
            gr.manousos.service.Contact _returnContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
            _returnContactTaxpayersVal1Contact.setCell("Cell-1552670190");
            _returnContactTaxpayersVal1Contact.setContactId(Integer.valueOf(285682967));
            _returnContactTaxpayersVal1Contact.setEmail("Email1637733923");
            _returnContactTaxpayersVal1Contact.setFax("Fax-187161110");
            _returnContactTaxpayersVal1Contact.setPhone("Phone636140030");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnContactTaxpayersVal1Contact.getTaxpayers().addAll(_returnContactTaxpayersVal1ContactTaxpayers);
            _returnContactTaxpayersVal1.setContact(_returnContactTaxpayersVal1Contact);
            _returnContactTaxpayersVal1.setFatherName("FatherName-1207693647");
            _returnContactTaxpayersVal1.setFname("Fname-459408773");
            _returnContactTaxpayersVal1.setId(Integer.valueOf(-1044759579));
            _returnContactTaxpayersVal1.setLname("Lname-1428540882");
            gr.manousos.service.User _returnContactTaxpayersVal1User = new gr.manousos.service.User();
            _returnContactTaxpayersVal1User.setActive(-413139314);
            _returnContactTaxpayersVal1User.setOtp("Otp-520703451");
            _returnContactTaxpayersVal1User.setPassword("Password315511940");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnContactTaxpayersVal1User.getTaxpayers().addAll(_returnContactTaxpayersVal1UserTaxpayers);
            _returnContactTaxpayersVal1User.setUserId(Integer.valueOf(73270174));
            _returnContactTaxpayersVal1User.setUserName("UserName396215196");
            _returnContactTaxpayersVal1.setUser(_returnContactTaxpayersVal1User);
            _returnContactTaxpayers.add(_returnContactTaxpayersVal1);
            _returnContact.getTaxpayers().addAll(_returnContactTaxpayers);
            _return.setContact(_returnContact);
            _return.setFatherName("FatherName-1043462934");
            _return.setFname("Fname1313794145");
            _return.setId(Integer.valueOf(-544161518));
            _return.setLname("Lname1079792969");
            gr.manousos.service.User _returnUser = new gr.manousos.service.User();
            _returnUser.setActive(384123133);
            _returnUser.setOtp("Otp-1568461429");
            _returnUser.setPassword("Password-38476250");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            gr.manousos.service.Taxpayer _returnUserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
            _returnUserTaxpayersVal1.setAfm("Afm389218048");
            gr.manousos.service.Contact _returnUserTaxpayersVal1Contact = new gr.manousos.service.Contact();
            _returnUserTaxpayersVal1Contact.setCell("Cell1441575464");
            _returnUserTaxpayersVal1Contact.setContactId(Integer.valueOf(-1997746003));
            _returnUserTaxpayersVal1Contact.setEmail("Email137560994");
            _returnUserTaxpayersVal1Contact.setFax("Fax1680717810");
            _returnUserTaxpayersVal1Contact.setPhone("Phone1795102791");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnUserTaxpayersVal1Contact.getTaxpayers().addAll(_returnUserTaxpayersVal1ContactTaxpayers);
            _returnUserTaxpayersVal1.setContact(_returnUserTaxpayersVal1Contact);
            _returnUserTaxpayersVal1.setFatherName("FatherName37067887");
            _returnUserTaxpayersVal1.setFname("Fname-1587684077");
            _returnUserTaxpayersVal1.setId(Integer.valueOf(-196037863));
            _returnUserTaxpayersVal1.setLname("Lname1773768954");
            gr.manousos.service.User _returnUserTaxpayersVal1User = new gr.manousos.service.User();
            _returnUserTaxpayersVal1User.setActive(54899483);
            _returnUserTaxpayersVal1User.setOtp("Otp702696342");
            _returnUserTaxpayersVal1User.setPassword("Password594963321");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnUserTaxpayersVal1User.getTaxpayers().addAll(_returnUserTaxpayersVal1UserTaxpayers);
            _returnUserTaxpayersVal1User.setUserId(Integer.valueOf(108783765));
            _returnUserTaxpayersVal1User.setUserName("UserName391200388");
            _returnUserTaxpayersVal1.setUser(_returnUserTaxpayersVal1User);
            _returnUserTaxpayers.add(_returnUserTaxpayersVal1);
            _returnUser.getTaxpayers().addAll(_returnUserTaxpayers);
            _returnUser.setUserId(Integer.valueOf(-355337738));
            _returnUser.setUserName("UserName575385768");
            _return.setUser(_returnUser);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrv#registerTaxPayer(gr.manousos.service.Taxpayer  arg0 )*
     */
    public void registerTaxPayer(gr.manousos.service.Taxpayer arg0) { 
        LOG.info("Executing operation registerTaxPayer");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
