
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gr.manousos.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-23T19:32:25.388+02:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserSrvImpl",
                      portName = "UserSrvImplPort",
                      targetNamespace = "http://service.manousos.gr/",
                      wsdlLocation = "http://localhost:8088/TaxisNetTestUI/services/UserSrvImplPort?wsdl",
                      endpointInterface = "gr.manousos.service.UserSrvImplPortType")
                      
public class UserSrvImplPortTypeImpl implements UserSrvImplPortType {

    private static final Logger LOG = Logger.getLogger(UserSrvImplPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrvImplPortType#test(java.lang.String  msg )*
     */
    public java.lang.String test(java.lang.String msg) { 
        LOG.info("Executing operation test");
        System.out.println(msg);
        try {
            java.lang.String _return = "_return-867526882";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrvImplPortType#register(gr.manousos.service.Taxpayer  user )*
     */
    public gr.manousos.service.Taxpayer register(gr.manousos.service.Taxpayer user) { 
        LOG.info("Executing operation register");
        System.out.println(user);
        try {
            gr.manousos.service.Taxpayer _return = new gr.manousos.service.Taxpayer();
            _return.setAfm("Afm-2041368731");
            gr.manousos.service.Contact _returnContact = new gr.manousos.service.Contact();
            _returnContact.setCell("Cell-2031945706");
            _returnContact.setContactId(Integer.valueOf(-1899831215));
            _returnContact.setEmail("Email-427246778");
            _returnContact.setFax("Fax-1120093085");
            _returnContact.setPhone("Phone1590467379");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            gr.manousos.service.Taxpayer _returnContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
            _returnContactTaxpayersVal1.setAfm("Afm-2072089994");
            gr.manousos.service.Contact _returnContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
            _returnContactTaxpayersVal1Contact.setCell("Cell1176744753");
            _returnContactTaxpayersVal1Contact.setContactId(Integer.valueOf(-70736080));
            _returnContactTaxpayersVal1Contact.setEmail("Email-1659077334");
            _returnContactTaxpayersVal1Contact.setFax("Fax-529434249");
            _returnContactTaxpayersVal1Contact.setPhone("Phone1061197190");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnContactTaxpayersVal1Contact.getTaxpayers().addAll(_returnContactTaxpayersVal1ContactTaxpayers);
            _returnContactTaxpayersVal1.setContact(_returnContactTaxpayersVal1Contact);
            _returnContactTaxpayersVal1.setFatherName("FatherName343173370");
            _returnContactTaxpayersVal1.setFname("Fname-1410265965");
            _returnContactTaxpayersVal1.setId(Integer.valueOf(908463620));
            _returnContactTaxpayersVal1.setLname("Lname1441668906");
            gr.manousos.service.User _returnContactTaxpayersVal1User = new gr.manousos.service.User();
            _returnContactTaxpayersVal1User.setActive(751081275);
            _returnContactTaxpayersVal1User.setOtp("Otp127151207");
            _returnContactTaxpayersVal1User.setPassword("Password1545849081");
            java.util.List<gr.manousos.service.Taxpayer> _returnContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnContactTaxpayersVal1User.getTaxpayers().addAll(_returnContactTaxpayersVal1UserTaxpayers);
            _returnContactTaxpayersVal1User.setUserId(Integer.valueOf(1462875297));
            _returnContactTaxpayersVal1User.setUserName("UserName389960530");
            _returnContactTaxpayersVal1.setUser(_returnContactTaxpayersVal1User);
            _returnContactTaxpayers.add(_returnContactTaxpayersVal1);
            _returnContact.getTaxpayers().addAll(_returnContactTaxpayers);
            _return.setContact(_returnContact);
            _return.setFatherName("FatherName-597774837");
            _return.setFname("Fname-115706089");
            _return.setId(Integer.valueOf(-1885825619));
            _return.setLname("Lname-691036337");
            gr.manousos.service.User _returnUser = new gr.manousos.service.User();
            _returnUser.setActive(-1043667059);
            _returnUser.setOtp("Otp1551705079");
            _returnUser.setPassword("Password1765156667");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            gr.manousos.service.Taxpayer _returnUserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
            _returnUserTaxpayersVal1.setAfm("Afm816294926");
            gr.manousos.service.Contact _returnUserTaxpayersVal1Contact = new gr.manousos.service.Contact();
            _returnUserTaxpayersVal1Contact.setCell("Cell2082728492");
            _returnUserTaxpayersVal1Contact.setContactId(Integer.valueOf(449243194));
            _returnUserTaxpayersVal1Contact.setEmail("Email-165513345");
            _returnUserTaxpayersVal1Contact.setFax("Fax1476228230");
            _returnUserTaxpayersVal1Contact.setPhone("Phone-1726800611");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnUserTaxpayersVal1Contact.getTaxpayers().addAll(_returnUserTaxpayersVal1ContactTaxpayers);
            _returnUserTaxpayersVal1.setContact(_returnUserTaxpayersVal1Contact);
            _returnUserTaxpayersVal1.setFatherName("FatherName-1820203259");
            _returnUserTaxpayersVal1.setFname("Fname-2011537315");
            _returnUserTaxpayersVal1.setId(Integer.valueOf(-934004126));
            _returnUserTaxpayersVal1.setLname("Lname388382860");
            gr.manousos.service.User _returnUserTaxpayersVal1User = new gr.manousos.service.User();
            _returnUserTaxpayersVal1User.setActive(-339988820);
            _returnUserTaxpayersVal1User.setOtp("Otp-1810568182");
            _returnUserTaxpayersVal1User.setPassword("Password1672656849");
            java.util.List<gr.manousos.service.Taxpayer> _returnUserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
            _returnUserTaxpayersVal1User.getTaxpayers().addAll(_returnUserTaxpayersVal1UserTaxpayers);
            _returnUserTaxpayersVal1User.setUserId(Integer.valueOf(-1585177376));
            _returnUserTaxpayersVal1User.setUserName("UserName1511878828");
            _returnUserTaxpayersVal1.setUser(_returnUserTaxpayersVal1User);
            _returnUserTaxpayers.add(_returnUserTaxpayersVal1);
            _returnUser.getTaxpayers().addAll(_returnUserTaxpayers);
            _returnUser.setUserId(Integer.valueOf(-944250893));
            _returnUser.setUserName("UserName205200026");
            _return.setUser(_returnUser);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gr.manousos.service.UserSrvImplPortType#registerTaxPayer(gr.manousos.service.Taxpayer  user )*
     */
    public void registerTaxPayer(gr.manousos.service.Taxpayer user) { 
        LOG.info("Executing operation registerTaxPayer");
        System.out.println(user);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
