
package gr.manousos.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-13T20:25:36.378+02:00
 * Generated source version: 2.7.0
 * 
 */
public final class UserSrv_UserSrvImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.manousos.gr/", "UserSrvImplService");

    private UserSrv_UserSrvImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserSrvImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserSrvImplService ss = new UserSrvImplService(wsdlURL, SERVICE_NAME);
        UserSrv port = ss.getUserSrvImplPort();  
        
        {
        System.out.println("Invoking test...");
        java.lang.String _test_arg0 = "_test_arg0-781009701";
        java.lang.String _test__return = port.test(_test_arg0);
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking getTaxPayerById...");
        int _getTaxPayerById_arg0 = -2122977396;
        gr.manousos.service.Taxpayer _getTaxPayerById__return = port.getTaxPayerById(_getTaxPayerById_arg0);
        System.out.println("getTaxPayerById.result=" + _getTaxPayerById__return);


        }
        {
        System.out.println("Invoking register...");
        gr.manousos.service.Taxpayer _register_arg0 = new gr.manousos.service.Taxpayer();
        _register_arg0.setAfm("Afm289489261");
        gr.manousos.service.Contact _register_arg0Contact = new gr.manousos.service.Contact();
        _register_arg0Contact.setCell("Cell1262341419");
        _register_arg0Contact.setContactId(Integer.valueOf(-1138681131));
        _register_arg0Contact.setEmail("Email-248444267");
        _register_arg0Contact.setFax("Fax2130736498");
        _register_arg0Contact.setPhone("Phone-887952246");
        java.util.List<gr.manousos.service.Taxpayer> _register_arg0ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _register_arg0ContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _register_arg0ContactTaxpayersVal1.setAfm("Afm-752304052");
        gr.manousos.service.Contact _register_arg0ContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _register_arg0ContactTaxpayersVal1Contact.setCell("Cell43180048");
        _register_arg0ContactTaxpayersVal1Contact.setContactId(Integer.valueOf(1547810342));
        _register_arg0ContactTaxpayersVal1Contact.setEmail("Email842463658");
        _register_arg0ContactTaxpayersVal1Contact.setFax("Fax1336348382");
        _register_arg0ContactTaxpayersVal1Contact.setPhone("Phone-1181843898");
        java.util.List<gr.manousos.service.Taxpayer> _register_arg0ContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_arg0ContactTaxpayersVal1Contact.getTaxpayers().addAll(_register_arg0ContactTaxpayersVal1ContactTaxpayers);
        _register_arg0ContactTaxpayersVal1.setContact(_register_arg0ContactTaxpayersVal1Contact);
        _register_arg0ContactTaxpayersVal1.setFatherName("FatherName-1248346775");
        _register_arg0ContactTaxpayersVal1.setFname("Fname-2127485416");
        _register_arg0ContactTaxpayersVal1.setId(Integer.valueOf(394164524));
        _register_arg0ContactTaxpayersVal1.setLname("Lname-1730529546");
        gr.manousos.service.User _register_arg0ContactTaxpayersVal1User = new gr.manousos.service.User();
        _register_arg0ContactTaxpayersVal1User.setActive(485184902);
        _register_arg0ContactTaxpayersVal1User.setOtp("Otp339337976");
        _register_arg0ContactTaxpayersVal1User.setPassword("Password1662675134");
        java.util.List<gr.manousos.service.Taxpayer> _register_arg0ContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_arg0ContactTaxpayersVal1User.getTaxpayers().addAll(_register_arg0ContactTaxpayersVal1UserTaxpayers);
        _register_arg0ContactTaxpayersVal1User.setUserId(Integer.valueOf(-585934490));
        _register_arg0ContactTaxpayersVal1User.setUserName("UserName-749761607");
        _register_arg0ContactTaxpayersVal1.setUser(_register_arg0ContactTaxpayersVal1User);
        _register_arg0ContactTaxpayers.add(_register_arg0ContactTaxpayersVal1);
        _register_arg0Contact.getTaxpayers().addAll(_register_arg0ContactTaxpayers);
        _register_arg0.setContact(_register_arg0Contact);
        _register_arg0.setFatherName("FatherName564591417");
        _register_arg0.setFname("Fname-252633565");
        _register_arg0.setId(Integer.valueOf(-207947333));
        _register_arg0.setLname("Lname1502086897");
        gr.manousos.service.User _register_arg0User = new gr.manousos.service.User();
        _register_arg0User.setActive(-373121782);
        _register_arg0User.setOtp("Otp-444534948");
        _register_arg0User.setPassword("Password-1683531382");
        java.util.List<gr.manousos.service.Taxpayer> _register_arg0UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _register_arg0UserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _register_arg0UserTaxpayersVal1.setAfm("Afm-388528426");
        gr.manousos.service.Contact _register_arg0UserTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _register_arg0UserTaxpayersVal1Contact.setCell("Cell1015350923");
        _register_arg0UserTaxpayersVal1Contact.setContactId(Integer.valueOf(-629634950));
        _register_arg0UserTaxpayersVal1Contact.setEmail("Email1403700654");
        _register_arg0UserTaxpayersVal1Contact.setFax("Fax-897003764");
        _register_arg0UserTaxpayersVal1Contact.setPhone("Phone-1662006841");
        java.util.List<gr.manousos.service.Taxpayer> _register_arg0UserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_arg0UserTaxpayersVal1Contact.getTaxpayers().addAll(_register_arg0UserTaxpayersVal1ContactTaxpayers);
        _register_arg0UserTaxpayersVal1.setContact(_register_arg0UserTaxpayersVal1Contact);
        _register_arg0UserTaxpayersVal1.setFatherName("FatherName680530566");
        _register_arg0UserTaxpayersVal1.setFname("Fname1978269019");
        _register_arg0UserTaxpayersVal1.setId(Integer.valueOf(50627257));
        _register_arg0UserTaxpayersVal1.setLname("Lname-1840981022");
        gr.manousos.service.User _register_arg0UserTaxpayersVal1User = new gr.manousos.service.User();
        _register_arg0UserTaxpayersVal1User.setActive(261317792);
        _register_arg0UserTaxpayersVal1User.setOtp("Otp-232163725");
        _register_arg0UserTaxpayersVal1User.setPassword("Password-513100732");
        java.util.List<gr.manousos.service.Taxpayer> _register_arg0UserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _register_arg0UserTaxpayersVal1User.getTaxpayers().addAll(_register_arg0UserTaxpayersVal1UserTaxpayers);
        _register_arg0UserTaxpayersVal1User.setUserId(Integer.valueOf(1145234318));
        _register_arg0UserTaxpayersVal1User.setUserName("UserName1434166122");
        _register_arg0UserTaxpayersVal1.setUser(_register_arg0UserTaxpayersVal1User);
        _register_arg0UserTaxpayers.add(_register_arg0UserTaxpayersVal1);
        _register_arg0User.getTaxpayers().addAll(_register_arg0UserTaxpayers);
        _register_arg0User.setUserId(Integer.valueOf(-1191570664));
        _register_arg0User.setUserName("UserName1456418144");
        _register_arg0.setUser(_register_arg0User);
        gr.manousos.service.Taxpayer _register__return = port.register(_register_arg0);
        System.out.println("register.result=" + _register__return);


        }
        {
        System.out.println("Invoking registerTaxPayer...");
        gr.manousos.service.Taxpayer _registerTaxPayer_arg0 = new gr.manousos.service.Taxpayer();
        _registerTaxPayer_arg0.setAfm("Afm-1540130109");
        gr.manousos.service.Contact _registerTaxPayer_arg0Contact = new gr.manousos.service.Contact();
        _registerTaxPayer_arg0Contact.setCell("Cell981004966");
        _registerTaxPayer_arg0Contact.setContactId(Integer.valueOf(1419975809));
        _registerTaxPayer_arg0Contact.setEmail("Email1554232136");
        _registerTaxPayer_arg0Contact.setFax("Fax1747933103");
        _registerTaxPayer_arg0Contact.setPhone("Phone179510557");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_arg0ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _registerTaxPayer_arg0ContactTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _registerTaxPayer_arg0ContactTaxpayersVal1.setAfm("Afm-1926195439");
        gr.manousos.service.Contact _registerTaxPayer_arg0ContactTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _registerTaxPayer_arg0ContactTaxpayersVal1Contact.setCell("Cell-1999910069");
        _registerTaxPayer_arg0ContactTaxpayersVal1Contact.setContactId(Integer.valueOf(2076676330));
        _registerTaxPayer_arg0ContactTaxpayersVal1Contact.setEmail("Email563238594");
        _registerTaxPayer_arg0ContactTaxpayersVal1Contact.setFax("Fax1577730981");
        _registerTaxPayer_arg0ContactTaxpayersVal1Contact.setPhone("Phone1535755147");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_arg0ContactTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_arg0ContactTaxpayersVal1Contact.getTaxpayers().addAll(_registerTaxPayer_arg0ContactTaxpayersVal1ContactTaxpayers);
        _registerTaxPayer_arg0ContactTaxpayersVal1.setContact(_registerTaxPayer_arg0ContactTaxpayersVal1Contact);
        _registerTaxPayer_arg0ContactTaxpayersVal1.setFatherName("FatherName813854957");
        _registerTaxPayer_arg0ContactTaxpayersVal1.setFname("Fname1003453719");
        _registerTaxPayer_arg0ContactTaxpayersVal1.setId(Integer.valueOf(-1796677075));
        _registerTaxPayer_arg0ContactTaxpayersVal1.setLname("Lname2950145");
        gr.manousos.service.User _registerTaxPayer_arg0ContactTaxpayersVal1User = new gr.manousos.service.User();
        _registerTaxPayer_arg0ContactTaxpayersVal1User.setActive(210603204);
        _registerTaxPayer_arg0ContactTaxpayersVal1User.setOtp("Otp2141026768");
        _registerTaxPayer_arg0ContactTaxpayersVal1User.setPassword("Password-1589343875");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_arg0ContactTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_arg0ContactTaxpayersVal1User.getTaxpayers().addAll(_registerTaxPayer_arg0ContactTaxpayersVal1UserTaxpayers);
        _registerTaxPayer_arg0ContactTaxpayersVal1User.setUserId(Integer.valueOf(-1855591485));
        _registerTaxPayer_arg0ContactTaxpayersVal1User.setUserName("UserName770576898");
        _registerTaxPayer_arg0ContactTaxpayersVal1.setUser(_registerTaxPayer_arg0ContactTaxpayersVal1User);
        _registerTaxPayer_arg0ContactTaxpayers.add(_registerTaxPayer_arg0ContactTaxpayersVal1);
        _registerTaxPayer_arg0Contact.getTaxpayers().addAll(_registerTaxPayer_arg0ContactTaxpayers);
        _registerTaxPayer_arg0.setContact(_registerTaxPayer_arg0Contact);
        _registerTaxPayer_arg0.setFatherName("FatherName-1825330251");
        _registerTaxPayer_arg0.setFname("Fname-240113563");
        _registerTaxPayer_arg0.setId(Integer.valueOf(1705229961));
        _registerTaxPayer_arg0.setLname("Lname-1617723402");
        gr.manousos.service.User _registerTaxPayer_arg0User = new gr.manousos.service.User();
        _registerTaxPayer_arg0User.setActive(2082175436);
        _registerTaxPayer_arg0User.setOtp("Otp-1757182978");
        _registerTaxPayer_arg0User.setPassword("Password723871341");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_arg0UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        gr.manousos.service.Taxpayer _registerTaxPayer_arg0UserTaxpayersVal1 = new gr.manousos.service.Taxpayer();
        _registerTaxPayer_arg0UserTaxpayersVal1.setAfm("Afm-213893093");
        gr.manousos.service.Contact _registerTaxPayer_arg0UserTaxpayersVal1Contact = new gr.manousos.service.Contact();
        _registerTaxPayer_arg0UserTaxpayersVal1Contact.setCell("Cell1126266038");
        _registerTaxPayer_arg0UserTaxpayersVal1Contact.setContactId(Integer.valueOf(930498374));
        _registerTaxPayer_arg0UserTaxpayersVal1Contact.setEmail("Email1722682865");
        _registerTaxPayer_arg0UserTaxpayersVal1Contact.setFax("Fax-360787500");
        _registerTaxPayer_arg0UserTaxpayersVal1Contact.setPhone("Phone-1947424167");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_arg0UserTaxpayersVal1ContactTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_arg0UserTaxpayersVal1Contact.getTaxpayers().addAll(_registerTaxPayer_arg0UserTaxpayersVal1ContactTaxpayers);
        _registerTaxPayer_arg0UserTaxpayersVal1.setContact(_registerTaxPayer_arg0UserTaxpayersVal1Contact);
        _registerTaxPayer_arg0UserTaxpayersVal1.setFatherName("FatherName-538707985");
        _registerTaxPayer_arg0UserTaxpayersVal1.setFname("Fname928699974");
        _registerTaxPayer_arg0UserTaxpayersVal1.setId(Integer.valueOf(-653165224));
        _registerTaxPayer_arg0UserTaxpayersVal1.setLname("Lname1782910911");
        gr.manousos.service.User _registerTaxPayer_arg0UserTaxpayersVal1User = new gr.manousos.service.User();
        _registerTaxPayer_arg0UserTaxpayersVal1User.setActive(1855579251);
        _registerTaxPayer_arg0UserTaxpayersVal1User.setOtp("Otp-1775817269");
        _registerTaxPayer_arg0UserTaxpayersVal1User.setPassword("Password-810171926");
        java.util.List<gr.manousos.service.Taxpayer> _registerTaxPayer_arg0UserTaxpayersVal1UserTaxpayers = new java.util.ArrayList<gr.manousos.service.Taxpayer>();
        _registerTaxPayer_arg0UserTaxpayersVal1User.getTaxpayers().addAll(_registerTaxPayer_arg0UserTaxpayersVal1UserTaxpayers);
        _registerTaxPayer_arg0UserTaxpayersVal1User.setUserId(Integer.valueOf(-600038083));
        _registerTaxPayer_arg0UserTaxpayersVal1User.setUserName("UserName-1576181908");
        _registerTaxPayer_arg0UserTaxpayersVal1.setUser(_registerTaxPayer_arg0UserTaxpayersVal1User);
        _registerTaxPayer_arg0UserTaxpayers.add(_registerTaxPayer_arg0UserTaxpayersVal1);
        _registerTaxPayer_arg0User.getTaxpayers().addAll(_registerTaxPayer_arg0UserTaxpayers);
        _registerTaxPayer_arg0User.setUserId(Integer.valueOf(-461272365));
        _registerTaxPayer_arg0User.setUserName("UserName368309070");
        _registerTaxPayer_arg0.setUser(_registerTaxPayer_arg0User);
        port.registerTaxPayer(_registerTaxPayer_arg0);


        }

        System.exit(0);
    }

}
